other-images-component-image-cy-561
caisy-io/league pull request #118
Opened 2021-12-10 12:53 UTC by steiningermona

2021-12-10 17:10 UTC, diegomart2000 commented
@steiningermona please meet PR Success checks

2021-12-10 19:32 UTC, diegomart2000 requested changes

2021-12-10 19:32 UTC, diegomart2000 commented on src/components/component-image/ComponentImage.tsx
> +  type?: IComponentImageTypes;
@steiningermona this needs to receive the image to be rendered.

2021-12-13 09:00 UTC, steiningermona commented
**from storybook**
![Bildschirmfoto 2021-12-13 um 09 59 21](https://user-images.githubusercontent.com/93647258/145782188-f87d7790-3135-4c75-bb42-9329ed839b20.png)
**from figma**
![Bildschirmfoto 2021-12-13 um 10 00 00](https://user-images.githubusercontent.com/93647258/145782238-8c8669a2-68a1-4835-bc4b-32b3876e0db9.png)

2021-12-15 12:21 UTC, diegomart2000 approved these changes

2021-12-17 11:21 UTC, merged