checkbox-component-cy-566
caisy-io/league pull request #130
Opened 2021-12-14 15:32 UTC by steiningermona

2021-12-14 18:17 UTC, steiningermona commented
**from storybook**
![image](https://user-images.githubusercontent.com/93647258/146056384-990d791c-0909-4020-b4b6-f29848177160.png)
![Bildschirmfoto 2021-12-14 um 19 16 29](https://user-images.githubusercontent.com/93647258/146056407-bc44d850-bfa3-4eae-a217-e35408029c60.png)
**from figma**
<img width="72" alt="Bildschirmfoto 2021-12-14 um 19 16 59" src="https://user-images.githubusercontent.com/93647258/146056463-ed049faa-c7a3-4b95-8f67-fc3943152f0b.png">

2021-12-15 13:13 UTC, diegomart2000 commented on src/components/checkbox/Checkbox.tsx
> +  onChange: (e: Event) => void,
🥳

2021-12-15 13:15 UTC, diegomart2000 requested changes

2021-12-15 13:15 UTC, diegomart2000 commented on src/icons/IconCheckmark.tsx
>  export function IconCheckmark() {
@steiningermona Please add the size to the interface.

2021-12-15 13:15 UTC, diegomart2000 commented on src/components/checkbox/Checkbox.tsx
> +        <IconCheckmark></IconCheckmark>
@steiningermona please add the size to conform with the interface.

2021-12-15 13:30 UTC, steiningermona commented on src/components/checkbox/Checkbox.tsx
> +  onChange: (e: Event) => void,
😍

2021-12-16 15:09 UTC, diegomart2000 approved these changes

2021-12-17 15:44 UTC, merged