default-tabs-cy-264-fixes
caisy-io/league pull request #159
Opened 2021-12-23 19:29 UTC by cris22380

2021-12-23 19:42 UTC, cris22380 commented
- From Storybook
![defaul1](https://user-images.githubusercontent.com/43223122/147285020-06e2a1f3-0f55-4bc0-a073-a18126638889.png)

- From Storybook
![defaul2](https://user-images.githubusercontent.com/43223122/147285021-d75a1c76-891b-4e37-9130-f1b0d1f1b6dd.png)

- From Storybook
![defaul3](https://user-images.githubusercontent.com/43223122/147285022-2be556d0-9c75-4956-805e-e96bb3114246.png)

- From Figma
![default figma](https://user-images.githubusercontent.com/43223122/147285023-c63df43a-9585-4c9b-b0c8-7613a030c5cd.png)

- From Storybook
![small2](https://user-images.githubusercontent.com/43223122/147285049-e567aea9-42ab-4f37-948e-04df947611c7.png)

- From Storybook
![small3](https://user-images.githubusercontent.com/43223122/147285051-73435c19-63d2-4970-a48d-9d926ea340ab.png)

- From Storybook
![small1](https://user-images.githubusercontent.com/43223122/147285046-34849b53-23f8-4d39-834d-653dcff4edb4.png)

- From Figma
![small figma](https://user-images.githubusercontent.com/43223122/147285044-bc356137-ec5a-4da1-bde9-bb159e7e4914.png)

- From Storybook
![MEDIUN1](https://user-images.githubusercontent.com/43223122/147285026-f528e0c3-0530-4e01-9e28-ad12361ab898.png)

- From Storybook
![MEDIUN2](https://user-images.githubusercontent.com/43223122/147285028-aa544a28-6967-4290-b483-50955aca6c1e.png)

- From Storybook
![MEDIUN3](https://user-images.githubusercontent.com/43223122/147285031-2194ca9d-8896-49cb-a47f-78c807a4846e.png)

- From Storybook
![MEDIUN figma](https://user-images.githubusercontent.com/43223122/147285203-6860fcdb-95bc-4445-809c-6afc7b1d64d9.png)

- From Storybook
![micro 1](https://user-images.githubusercontent.com/43223122/147285033-a114336f-b070-47ae-aa77-ef21ccfdb328.png)

- From Storybook
![micro 2](https://user-images.githubusercontent.com/43223122/147285035-f3ef3fc5-f29e-4a14-9986-7efc055f76f0.png)

- From Storybook
![micro 3](https://user-images.githubusercontent.com/43223122/147285036-3ef8b4ca-c040-49c4-a0ba-60a1cbe774d5.png)

- From Storybook
![micro 4](https://user-images.githubusercontent.com/43223122/147285038-339893ed-d071-4d80-971f-2ae6a81631db.png)

- From Figma
![micro figma](https://user-images.githubusercontent.com/43223122/147285042-13c25750-0418-4f94-a621-a19c9a609c32.png)

2021-12-24 15:21 UTC, diegomart2000 requested changes

2021-12-24 15:21 UTC, diegomart2000 commented on src/components/tab/Tab.stories.tsx
> +  console.log(args)
@cris22380 please remove console.log

2021-12-27 17:54 UTC, diegomart2000 approved these changes

2021-12-28 20:36 UTC, merged