regular-pop-up-menu-cy-229
caisy-io/league pull request #163
Opened 2021-12-27 19:22 UTC by cris22380

2021-12-27 19:28 UTC, cris22380 commented
- From storybook
![pop up scroll storybook](https://user-images.githubusercontent.com/43223122/147501470-20bb8d7d-2da7-4184-bb6e-0e16f244aa46.png)

- From Figma
![pop up scrollfigma](https://user-images.githubusercontent.com/43223122/147501473-8bd1f5c1-a234-4ace-9889-6e533b1fae9e.png)

- From storybook
![pop up storybook](https://user-images.githubusercontent.com/43223122/147501457-0b02127b-9c44-46ff-b6b2-7fa696bde4d9.png)

- From Figma
![pop up figma](https://user-images.githubusercontent.com/43223122/147501463-a4a5f887-1f93-4e00-bf97-4afc2eff6b98.png)

2021-12-27 20:39 UTC, diegomart2000 requested changes

2021-12-27 20:39 UTC, diegomart2000 commented on src/components/regular-pop-up-menu/RegularPopUpMenu.stories.tsx
> +          <SPopUpHeader>
@cris22380 Styled components should not be exposed.

2021-12-27 20:39 UTC, diegomart2000 commented on src/components/regular-pop-up-menu/RegularPopUpMenu.stories.tsx
> +            <ModalHeader onClose={() => setToogleModal(false)}>
This is internal implementation. Should not be exposed. These 2 values should be passed as props.

2021-12-27 20:39 UTC, diegomart2000 commented on src/components/regular-pop-up-menu/RegularPopUpMenu.stories.tsx
> +          <SPopUpContent>
This is internal implmentation, should not be exposed. Main component should receive child items only.

2021-12-27 20:59 UTC, diegomart2000 commented
@cris22380 follow stories in here https://league-qodxxzzkp-caisy.vercel.app/?path=/story/components-menus-popovers-modal--default also move the stories under this category.

2021-12-27 21:00 UTC, diegomart2000 requested changes

2021-12-27 21:00 UTC, diegomart2000 commented on src/components/regular-pop-up-menu/RegularPopUpMenu.stories.tsx
> +  title: "Components/RegularPopUpmenu/PopUp",
Move to proper category already in place and make sure name is properly spelled.

2021-12-31 13:40 UTC, diegomart2000 requested changes

2021-12-31 13:40 UTC, diegomart2000 commented on src/components/regular-pop-up-menu/RegularPopUpMenu.tsx
> +import { ModalHeader } from "..";
@cris22380 avoid these kind of imports. This causes circular references, use named imports

2021-12-31 13:40 UTC, diegomart2000 commented on src/components/regular-pop-up-menu/styles/SPopUpHeader.tsx
> +width: 100%;
@cris22380 fix formatting.

2022-01-03 21:07 UTC, diegomart2000 approved these changes

2022-01-04 14:56 UTC, merged