uploads-pop-up-cy-253
caisy-io/league pull request #180
Opened 2022-01-10 19:35 UTC by cris22380

2022-01-12 12:16 UTC, diegomart2000 requested changes
<img width="636" alt="Screen Shot 2022-01-12 at 9 13 28 AM" src="https://user-images.githubusercontent.com/642960/149138448-6d693c5d-c7f5-4ab6-bee5-9788e9c9ea1f.png">

Icon is wrong, missing container styles.

2022-01-12 12:16 UTC, diegomart2000 commented on src/components/uploads-pop-up/styles/SUploadsPopup.tsx
> +display: flex;
@cris22380 fix this format error.

2022-01-12 12:16 UTC, diegomart2000 commented on src/components/uploads-pop-up/UploadsPopup.tsx
> +          <FlatActionButton type="grey">Clear</FlatActionButton>
@cris22380 clear button needs a callback.

2022-01-12 12:16 UTC, diegomart2000 commented on src/components/uploads-pop-up/UploadsPopup.tsx
> +    {children}
@cris22380 missing see all assets button.

2022-01-12 13:39 UTC, cris22380 commented
- From Storybook

![Screen Shot 2022-01-12 at 10 34 09](https://user-images.githubusercontent.com/43223122/149150489-342ef8bc-7d88-4b6c-ad14-6ec77cb15caa.png)

- From Storybook

![Screen Shot 2022-01-12 at 10 34 26](https://user-images.githubusercontent.com/43223122/149150498-5565baf1-1b86-4891-ba3a-87d3a22671ae.png)

- From figma

![Screen Shot 2022-01-12 at 10 36 19](https://user-images.githubusercontent.com/43223122/149150501-4c328bca-1a8f-4898-aea3-6416679f0c5d.png)

- From figma

![Screen Shot 2022-01-12 at 10 37 52](https://user-images.githubusercontent.com/43223122/149150770-a9acafa0-eabb-41ee-a141-71d3e6be8248.png)

2022-01-17 13:54 UTC, diegomart2000 approved these changes

2022-01-27 09:06 UTC, merged