organization-menu-list-item-cy-217
caisy-io/league pull request #80
Opened 2021-11-26 16:04 UTC by steiningermona

2021-11-29 18:58 UTC, diegomart2000 requested changes
@steiningermona please rebase from dev.

2021-12-02 13:30 UTC, diegomart2000 requested changes

2021-12-02 13:30 UTC, diegomart2000 commented on src/components/badge/Badge.tsx
> +export const Badge: React.FC<IBadgeProps> = ({ children, ...props }) => {
Prefer destructuring and named imports for react. Also badge is not working properly. Test here https://league-pxa6boiva-caisy.vercel.app/?path=/story/components-badge--position-left&args=type:color;value:11

2021-12-02 14:17 UTC, diegomart2000 requested changes

2021-12-02 14:17 UTC, diegomart2000 commented on src/components/organization-menu-list-item/OrganizationMenuListItem.tsx
> +export const OrganizationMenuListItem: React.FC<IOrganizationMenuListItemProps> = ({ ...props }) => {
Prefer destructuring and named imports. Only pass down used properties. Make sure component won't break on larger pieces of content.

https://league-pxa6boiva-caisy.vercel.app/?path=/story/components-organizationmenulistitem--default&args=title:Label+kkkk+dsdf+dsfsdfw+wer+wer+werwe+rwer+we+rwer;label:Label+kkkk+dsdf+dsfsdfw+wer+wer+werwe+rwer+we+rwer;size:small

2021-12-02 14:17 UTC, diegomart2000 commented on src/components/preview-flag-round/PreviewFlagRound.tsx
> +const PreviewFlagRound: FC<IFlag> = ({ countryCode }) => {
This component is repeated and not actually needed, let's discuss on why the original is not being used.

2021-12-02 14:17 UTC, diegomart2000 commented on src/components/preview-icon/PreviewIcon.stories.tsx
> +function PreviewIconDemo(args) {
This component is repeated and not actually needed, let's discuss on why the original is not being used.

2021-12-02 14:17 UTC, diegomart2000 commented on src/components/preview-icon/PreviewIcon.tsx
> +export const PreviewIcon: React.FC<IPreviewIcon> = ({ icon, ...props }) => {
This component is repeated and not actually needed, let's discuss on why the original is not being used.

2021-12-07 13:50 UTC, steiningermona commented
**from figma**
![image](https://user-images.githubusercontent.com/93647258/145040973-bc30c551-3872-4a94-8e5f-6921f43fd72e.png)

2021-12-07 20:53 UTC, diegomart2000 approved these changes

2021-12-07 20:54 UTC, merged