badges-cy-109
caisy-io/league pull request #85
Opened 2021-11-29 09:54 UTC by steiningermona

I had already opened a PR but I noticed that the resizing of the badge had to be done differently (in comparison to before) if the badge contains more than one character

2021-11-29 19:08 UTC, diegomart2000 requested changes

2021-11-29 19:08 UTC, diegomart2000 commented on src/components/badge/Badge.tsx
> +export type IBadgeSizeType = "micro" | "small" | "medium";
@steiningermona  Coordinate with @nicolasshiken to make this a general type.

2021-11-29 19:08 UTC, diegomart2000 commented on src/components/badge/Badge.tsx
> +      <SBadgeIcon {...props}>
only pass down required props.

2021-11-29 19:08 UTC, diegomart2000 commented on src/components/badge/Badge.tsx
> +export const Badge: React.FC<IBadgeProps> = ({ children, ...props }) => {
Prefer destructuring and React named imports.

2021-12-02 17:30 UTC, diegomart2000 requested changes
@steiningermona Badges in different styles don't match specifications.

<img width="136" alt="Screen Shot 2021-12-02 at 2 28 26 PM" src="https://user-images.githubusercontent.com/642960/144472925-c2987d3c-1765-4ee6-a9d1-b430295ee1f7.png">
^^No white borer in specs.

<img width="120" alt="Screen Shot 2021-12-02 at 2 27 25 PM" src="https://user-images.githubusercontent.com/642960/144473085-b98328e1-7b1c-4a32-8219-4caa86057971.png">
^^Wrong color

2021-12-07 11:56 UTC, steiningermona commented
**from storybook**
![image](https://user-images.githubusercontent.com/93647258/145017506-b5824c60-cbe1-4a66-803a-075b39a0a053.png)
![image](https://user-images.githubusercontent.com/93647258/145017524-65d924d8-f599-4e8f-954d-1b9ae340c4ce.png)
![image](https://user-images.githubusercontent.com/93647258/145017546-feab5823-ad0d-4eed-b2b2-b6ca18cda525.png)
![image](https://user-images.githubusercontent.com/93647258/145017576-b2097e4f-b8f2-422a-93b3-a1c66675aca2.png)
![image](https://user-images.githubusercontent.com/93647258/145017625-45fa781d-75cf-4aac-8f68-8d53dd86ea4a.png)

2021-12-07 20:55 UTC, diegomart2000 approved these changes

2021-12-07 20:55 UTC, merged