outline-label-mediumlarge-cy-169
caisy-io/league pull request #87
Opened 2021-11-29 13:32 UTC by cris22380

2021-11-29 19:11 UTC, diegomart2000 requested changes

2021-11-29 19:11 UTC, diegomart2000 commented on src/components/out-line-label/OutLineLabel.tsx
> +const OutLineLabel: FC<IOutLineLabel> = props => {
use props destructuring.

2021-11-29 19:11 UTC, diegomart2000 commented on src/components/out-line-label/OutLineLabel.tsx
> +      {props.colorLabel && <SColorLabelWrapper {...props}>{props.colorLabel}</SColorLabelWrapper>}
Only pass down required properties.

2021-11-29 19:11 UTC, diegomart2000 commented on src/components/out-line-label/styles/SIconWrapper.tsx
> +  size?: 'medium' | 'large';
This size interface is going to be a global type. Will let you know.

2021-12-06 18:57 UTC, cris22380 commented
![Screen Shot 2021-12-06 at 15 29 13](https://user-images.githubusercontent.com/43223122/144901989-8337b80f-cd0f-4086-bcea-55e7fed4d229.png)
![Screen Shot 2021-12-06 at 15 29 24](https://user-images.githubusercontent.com/43223122/144901993-1e37656a-4cb1-4951-accd-afc1a5560dc1.png)
![Screen Shot 2021-12-06 at 15 29 43](https://user-images.githubusercontent.com/43223122/144901994-0714f83f-fc87-47a4-ae28-4349b389a473.png)
![Screen Shot 2021-12-06 at 15 30 57](https://user-images.githubusercontent.com/43223122/144901998-79d57e39-932e-4038-bcc5-2aa43cc2d1ae.png)
![Screen Shot 2021-12-06 at 15 34 21](https://user-images.githubusercontent.com/43223122/144902648-174219ee-a630-4aa5-8fad-3904fa5af9e5.png)
![Screen Shot 2021-12-06 at 15 34 37](https://user-images.githubusercontent.com/43223122/144902653-6d7c16f3-8718-46b3-94e1-c37985cc0c9e.png)
![Screen Shot 2021-12-06 at 15 34 54](https://user-images.githubusercontent.com/43223122/144902659-3bfba3fb-6f5a-47a3-94ee-46e3f8c0531a.png)
![Screen Shot 2021-12-06 at 15 35 44](https://user-images.githubusercontent.com/43223122/144902662-69023020-2237-4de3-b433-3ab312e36573.png)
![Screen Shot 2021-12-06 at 15 40 20](https://user-images.githubusercontent.com/43223122/144903347-8a960414-a213-42e6-a6ba-341727def87f.png)
![Screen Shot 2021-12-06 at 15 40 32](https://user-images.githubusercontent.com/43223122/144903357-cc97b5ce-9c64-434b-b5df-f7ac059bd3fe.png)
![Screen Shot 2021-12-06 at 15 40 40](https://user-images.githubusercontent.com/43223122/144903360-d3e42e6b-b850-4094-94bb-ad25f2c40a5c.png)
![Screen Shot 2021-12-06 at 15 41 25](https://user-images.githubusercontent.com/43223122/144903364-57816aa7-1166-46ba-99bb-53c49e5954b1.png)
![Screen Shot 2021-12-06 at 15 41 59](https://user-images.githubusercontent.com/43223122/144903549-0a7f25dc-54b2-4c28-b07c-f9e893a60890.png)
![Screen Shot 2021-12-06 at 15 42 07](https://user-images.githubusercontent.com/43223122/144903551-c3ec59f7-3416-47bb-8e94-ec93c621513d.png)
![Screen Shot 2021-12-06 at 15 42 16](https://user-images.githubusercontent.com/43223122/144903555-4ebce3c0-a42d-401f-8f93-a5df743ce056.png)
![Screen Shot 2021-12-06 at 15 42 49](https://user-images.githubusercontent.com/43223122/144903557-b04a213d-e470-4037-81ab-44ff911a8930.png)
![Screen Shot 2021-12-06 at 15 45 20](https://user-images.githubusercontent.com/43223122/144904067-fd52070f-89e0-4e22-b5a5-7f445d386ddf.png)
![Screen Shot 2021-12-06 at 15 45 39](https://user-images.githubusercontent.com/43223122/144904071-75723e7c-f85b-42db-8349-e1e9896fc59f.png)
![Screen Shot 2021-12-06 at 15 45 57](https://user-images.githubusercontent.com/43223122/144904073-18d33f81-0c45-4811-839b-44af68fc44d5.png)
![Screen Shot 2021-12-06 at 15 46 27](https://user-images.githubusercontent.com/43223122/144904076-cd002231-8ff5-4b4a-a17e-d41d7b071d4c.png)
![Screen Shot 2021-12-06 at 15 47 37](https://user-images.githubusercontent.com/43223122/144904331-830740ef-fe41-4a9e-9041-295779d4ec71.png)
![Screen Shot 2021-12-06 at 15 47 58](https://user-images.githubusercontent.com/43223122/144904338-37f46f64-1290-47cf-ad98-6d8592d4d005.png)
![Screen Shot 2021-12-06 at 15 48 07](https://user-images.githubusercontent.com/43223122/144904341-1bc97b51-94f2-4a0b-a010-ca33fc4de47e.png)
![Screen Shot 2021-12-06 at 15 48 33](https://user-images.githubusercontent.com/43223122/144904344-71c5427b-6b0e-4de9-8fdc-797e1d12bae9.png)
![Screen Shot 2021-12-06 at 15 48 39](https://user-images.githubusercontent.com/43223122/144904347-dfaa1b34-3a8f-4e25-a6d2-70959edc0641.png)
![Screen Shot 2021-12-06 at 15 49 13](https://user-images.githubusercontent.com/43223122/144904571-b8326745-062a-49ff-a9b1-283a6637672d.png)
![Screen Shot 2021-12-06 at 15 49 22](https://user-images.githubusercontent.com/43223122/144904575-13d95ffe-6f85-4283-9d32-39bb369bd408.png)
![Screen Shot 2021-12-06 at 15 49 34](https://user-images.githubusercontent.com/43223122/144904578-3fab1d52-d6f8-44b0-8edb-e59ff14a4886.png)
![Screen Shot 2021-12-06 at 15 49 59](https://user-images.githubusercontent.com/43223122/144904582-ec47f33b-1254-410a-a631-740c08d896d6.png)
![Screen Shot 2021-12-06 at 15 50 05](https://user-images.githubusercontent.com/43223122/144904584-9f5f67b4-732f-41f5-9262-56b22a8e805b.png)
![Screen Shot 2021-12-06 at 15 52 18](https://user-images.githubusercontent.com/43223122/144905070-a3df6830-48a5-40dd-8c5d-4e61cef1756a.png)
![Screen Shot 2021-12-06 at 15 52 29](https://user-images.githubusercontent.com/43223122/144905073-e6f0da67-f590-402f-97aa-5fdab28ff425.png)
![Screen Shot 2021-12-06 at 15 52 40](https://user-images.githubusercontent.com/43223122/144905077-ff895cd2-f06f-4486-889d-bb814d0e83ee.png)
![Screen Shot 2021-12-06 at 15 53 13](https://user-images.githubusercontent.com/43223122/144905079-f01967d3-7cdc-40c1-be9c-63e66b2165f3.png)
![Screen Shot 2021-12-06 at 15 53 24](https://user-images.githubusercontent.com/43223122/144905080-1d55b2f2-79b8-49da-8d27-19d3bcc88df8.png)
![Screen Shot 2021-12-06 at 15 55 13](https://user-images.githubusercontent.com/43223122/144905376-5fa8f531-a810-44a9-8143-4898d00ad387.png)
![Screen Shot 2021-12-06 at 15 55 23](https://user-images.githubusercontent.com/43223122/144905378-28e634a0-35da-4eef-8e81-0f271b9f93a5.png)
![Screen Shot 2021-12-06 at 15 55 31](https://user-images.githubusercontent.com/43223122/144905380-83ad195a-e98f-44ad-9024-0f180f924ad5.png)
![Screen Shot 2021-12-06 at 15 56 00](https://user-images.githubusercontent.com/43223122/144905382-388f7d48-4740-4f89-a3f6-13f2580be8b8.png)
![Screen Shot 2021-12-06 at 15 56 06](https://user-images.githubusercontent.com/43223122/144905387-8ee66c43-c24a-4a6a-98de-bb1b63053e0a.png)

2021-12-07 18:42 UTC, diegomart2000 approved these changes

2021-12-07 18:43 UTC, merged