notifications-group-select-list-item-cy-219
caisy-io/league pull request #90
Opened 2021-12-01 08:41 UTC by steiningermona

There are so many changed files because I had to use the previews component in this component.

2021-12-06 15:23 UTC, steiningermona commented
**from figma**
![image](https://user-images.githubusercontent.com/93647258/144872510-aac49488-042a-4234-8360-579decbbee12.png)
**from storybook**
![image](https://user-images.githubusercontent.com/93647258/144872597-6d7fe9b6-2532-48e0-8b3b-878b5703029a.png)
hover:
![image](https://user-images.githubusercontent.com/93647258/144873031-10018f2e-66d5-433f-ae14-5a9d1cad969f.png)
active:
![image](https://user-images.githubusercontent.com/93647258/144873064-a45b06f3-9de3-4b81-ad2e-dd09ab9b8eed.png)
activated:
![image](https://user-images.githubusercontent.com/93647258/144872661-7306e43a-fa34-4b6d-8398-184bcc6cfa23.png)

2021-12-06 17:39 UTC, diegomart2000 requested changes

2021-12-06 17:39 UTC, diegomart2000 commented on src/components/notifications-group-select-list-item/NotificationsGroupSelectListItem.tsx
> +      <IconChevronDown></IconChevronDown>
@steiningermona 

[] If your component has a value it also needs a way to set that value, pass an onChange event.

--- In this case, the ChevronDown needs a onClick handler to be passed to notify parent to activate this item.

2021-12-06 17:39 UTC, diegomart2000 commented on src/components/notifications-group-select-list-item/NotificationsGroupSelectListItem.tsx
> +        <SNotificationsGroupSelectListItemTitle>{title}</SNotificationsGroupSelectListItemTitle>
@steiningermona Multiple words with white spaces break the component.

![Uploading Screen Shot 2021-12-06 at 2.38.18 PM.png…]()

2021-12-07 16:32 UTC, steiningermona commented
**from figma**
![image](https://user-images.githubusercontent.com/93647258/145068398-46b3bdfa-6110-4667-832a-7fcbc3ea3a95.png)
**from storybook**
![image](https://user-images.githubusercontent.com/93647258/145068530-14c95652-f5c2-4998-9843-b40d0c379b8c.png)
activated:
![image](https://user-images.githubusercontent.com/93647258/145068566-4acf4e9f-4f28-4c58-a585-817e2a52e2f0.png)

2021-12-13 11:59 UTC, diegomart2000 approved these changes

2021-12-13 11:59 UTC, merged