main-navigation-icons-cy-95
caisy-io/league pull request #91
Opened 2021-12-01 21:11 UTC by cris22380

2021-12-01 21:17 UTC, diegomart2000 requested changes

2021-12-01 21:17 UTC, diegomart2000 commented on src/icons/IconCross.tsx
> +const IconBase = styled.svg<{size: number}>`
This doesn't seem ok here.

2021-12-01 21:17 UTC, diegomart2000 commented on src/icons/IconDocumentsComponents.tsx
> +
Please remove unnecessary spaces.

2021-12-01 21:17 UTC, diegomart2000 commented on src/icons/IconTerminal.tsx
> +      <path d="M8.66663 10H10.6666" stroke="#172C55" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" />
You should remove the stroke color inline style which is coming from base icon.

2021-12-01 21:17 UTC, diegomart2000 commented on src/icons/IconTerminal.tsx
> +      <path d="M8.66663 10H10.6666" stroke="#172C55" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" />
This is a comment that applies to all the icons.

2021-12-06 17:58 UTC, cris22380 commented
![Screen Shot 2021-12-06 at 14 42 58](https://user-images.githubusercontent.com/43223122/144895348-a53f3846-29d5-46f7-b96e-dd0b3c458228.png)
![Screen Shot 2021-12-06 at 14 43 15](https://user-images.githubusercontent.com/43223122/144895353-c72c68d2-9b47-4cad-8e61-e1752d057b29.png)
![Screen Shot 2021-12-06 at 14 43 29](https://user-images.githubusercontent.com/43223122/144895354-21ef5cb6-98d6-4171-989f-f3486fac9c7f.png)
![Screen Shot 2021-12-06 at 14 43 39](https://user-images.githubusercontent.com/43223122/144895355-f90bde1f-ac60-475c-879e-dcf97099d620.png)
![Screen Shot 2021-12-06 at 14 43 52](https://user-images.githubusercontent.com/43223122/144895358-5714ac80-2a5b-444d-a2c2-c138b42a42f5.png)
![Screen Shot 2021-12-06 at 14 25 17](https://user-images.githubusercontent.com/43223122/144893538-0438d247-d00d-4b88-8278-53c591bb538a.png)
![Screen Shot 2021-12-06 at 14 27 04](https://user-images.githubusercontent.com/43223122/144893542-c4e0d031-d144-4c06-b8db-ab4eb16cff2a.png)
![Screen Shot 2021-12-06 at 14 27 33](https://user-images.githubusercontent.com/43223122/144893545-cd2db13b-2a06-4244-be66-212125be339f.png)
![Screen Shot 2021-12-06 at 14 28 04](https://user-images.githubusercontent.com/43223122/144893548-6c363843-1b32-41dc-94fd-37f5e5d4bd54.png)
![Screen Shot 2021-12-06 at 14 31 02](https://user-images.githubusercontent.com/43223122/144893549-fdc3d992-9b99-4aaa-a240-378067b11d80.png)
![Screen Shot 2021-12-06 at 14 32 41](https://user-images.githubusercontent.com/43223122/144893827-2f90862b-995d-4da0-ba60-b0e6fa7871b4.png)
![Screen Shot 2021-12-06 at 14 32 54](https://user-images.githubusercontent.com/43223122/144893833-c0383f32-3c24-42a9-bc0b-4024b10c132f.png)
![Screen Shot 2021-12-06 at 14 33 06](https://user-images.githubusercontent.com/43223122/144893835-54cadf76-2213-4cc9-87fc-6c907175a650.png)
![Screen Shot 2021-12-06 at 14 33 17](https://user-images.githubusercontent.com/43223122/144893839-af70266b-2b1f-4738-b6b2-5173aaf06431.png)
![Screen Shot 2021-12-06 at 14 33 31](https://user-images.githubusercontent.com/43223122/144893841-ad583be2-f348-424b-97be-4a46b51e6e3a.png)
![Screen Shot 2021-12-06 at 14 34 29](https://user-images.githubusercontent.com/43223122/144894115-e52a4f34-b325-4687-bc51-48e4c68cf74a.png)
![Screen Shot 2021-12-06 at 14 34 39](https://user-images.githubusercontent.com/43223122/144894118-df12fdc5-8dc6-45e6-a749-40347b129cc3.png)
![Screen Shot 2021-12-06 at 14 34 53](https://user-images.githubusercontent.com/43223122/144894121-b40283ec-44e0-4610-91bb-2113a9dd1ad2.png)
![Screen Shot 2021-12-06 at 14 35 02](https://user-images.githubusercontent.com/43223122/144894125-b893c3b3-fe31-40f0-8470-ec6da9a1f94c.png)
![Screen Shot 2021-12-06 at 14 35 24](https://user-images.githubusercontent.com/43223122/144894129-3d52bac4-0e22-419f-b1aa-9c2fac5866ad.png)
![Screen Shot 2021-12-06 at 14 36 27](https://user-images.githubusercontent.com/43223122/144894352-3b8042cc-4999-425f-84fe-df01078c1c15.png)
![Screen Shot 2021-12-06 at 14 36 37](https://user-images.githubusercontent.com/43223122/144894358-d8e52d2d-6bf3-456a-87e7-3638c8f6cac7.png)
![Screen Shot 2021-12-06 at 14 36 46](https://user-images.githubusercontent.com/43223122/144894362-5d1f2511-ab9e-48fa-9e10-68c980cb26a5.png)
![Screen Shot 2021-12-06 at 14 36 56](https://user-images.githubusercontent.com/43223122/144894363-091e6642-a1fb-47e7-b1b6-7882278334c4.png)
![Screen Shot 2021-12-06 at 14 37 08](https://user-images.githubusercontent.com/43223122/144894367-7c737091-8369-4f70-8a0e-ba41d32a53ae.png)
![Screen Shot 2021-12-06 at 14 38 14](https://user-images.githubusercontent.com/43223122/144894617-d392dfbd-99d8-424e-b984-4f9449209494.png)
![Screen Shot 2021-12-06 at 14 38 28](https://user-images.githubusercontent.com/43223122/144894776-c22e7a85-b7ad-435d-8306-6b1eeae9e91e.png)
![Screen Shot 2021-12-06 at 14 38 40](https://user-images.githubusercontent.com/43223122/144894784-df167019-cc41-4a3b-ac61-2be4ffd37749.png)
![Screen Shot 2021-12-06 at 14 38 52](https://user-images.githubusercontent.com/43223122/144894786-9bca2d5b-893c-463c-ae3e-0252463f24e3.png)
![Screen Shot 2021-12-06 at 14 39 07](https://user-images.githubusercontent.com/43223122/144894791-db112cbf-b4e0-4159-a820-c4b8a0a20ca2.png)
![Screen Shot 2021-12-06 at 14 41 06](https://user-images.githubusercontent.com/43223122/144895040-3fa500d5-65dc-4aab-9c10-8e338e0ec0a0.png)
![Screen Shot 2021-12-06 at 14 41 18](https://user-images.githubusercontent.com/43223122/144895046-7f443306-9a0e-465b-8e60-952265ad7412.png)
![Screen Shot 2021-12-06 at 14 41 31](https://user-images.githubusercontent.com/43223122/144895050-c5dcd68c-13f4-4929-b1a4-a211816ec988.png)
![Screen Shot 2021-12-06 at 14 41 44](https://user-images.githubusercontent.com/43223122/144895052-ef908c95-c439-405e-a527-150e97c7c0de.png)
![Screen Shot 2021-12-06 at 14 41 57](https://user-images.githubusercontent.com/43223122/144895054-741ded0d-1c98-4fad-8716-c1ff80920f61.png)
![Screen Shot 2021-12-06 at 14 44 57](https://user-images.githubusercontent.com/43223122/144895794-068460ed-0925-4570-99fe-bfed24e0825e.png)
![Screen Shot 2021-12-06 at 14 45 13](https://user-images.githubusercontent.com/43223122/144895800-b4479a64-42fd-4933-9ef4-c750037919ea.png)
![Screen Shot 2021-12-06 at 14 45 40](https://user-images.githubusercontent.com/43223122/144895803-42f8f0b1-9edc-4a08-95b3-3e44b6930535.png)
![Screen Shot 2021-12-06 at 14 45 56](https://user-images.githubusercontent.com/43223122/144895804-d3825a28-f55b-4a3b-833c-97fbad29eebb.png)
![Screen Shot 2021-12-06 at 14 46 24](https://user-images.githubusercontent.com/43223122/144895806-c985b732-3a3b-4927-a4bc-6337f5ed648e.png)
![Screen Shot 2021-12-06 at 14 49 07](https://user-images.githubusercontent.com/43223122/144896469-04dc24a0-0b18-4228-89ff-d2cdd8e8a137.png)
![Screen Shot 2021-12-06 at 14 49 37](https://user-images.githubusercontent.com/43223122/144896475-3c2300c9-ea8c-43f4-9a25-ac4334d6e05c.png)
![Screen Shot 2021-12-06 at 14 49 52](https://user-images.githubusercontent.com/43223122/144896477-d24052d5-8161-465b-9b81-f149bd86711b.png)
![Screen Shot 2021-12-06 at 14 50 38](https://user-images.githubusercontent.com/43223122/144896479-8975853b-e566-482b-ae38-1e42d35b0962.png)
![Screen Shot 2021-12-06 at 14 50 52](https://user-images.githubusercontent.com/43223122/144896481-d67ffd05-5f42-4089-a7f5-82bfd29e362f.png)
![Screen Shot 2021-12-06 at 14 52 28](https://user-images.githubusercontent.com/43223122/144897028-e3e71590-cdc4-4c1a-85b8-d5412fb7bd83.png)
![Screen Shot 2021-12-06 at 14 52 50](https://user-images.githubusercontent.com/43223122/144897032-7ebcf3fe-0070-4836-882c-983a1a21ea36.png)
![Screen Shot 2021-12-06 at 14 53 10](https://user-images.githubusercontent.com/43223122/144897039-a4e97daa-fe15-4d81-9c21-d75e3bb325b0.png)
![Screen Shot 2021-12-06 at 14 53 57](https://user-images.githubusercontent.com/43223122/144897043-fe8fba53-66f1-44e0-9749-7b2ecea52185.png)
![Screen Shot 2021-12-06 at 14 54 08](https://user-images.githubusercontent.com/43223122/144897045-1481eec6-c9a1-45a7-877f-eec8a021c95c.png)
![Screen Shot 2021-12-06 at 14 56 29](https://user-images.githubusercontent.com/43223122/144897460-dad04cf3-2c65-4a03-9f60-b22593c5eae0.png)
![Screen Shot 2021-12-06 at 14 56 38](https://user-images.githubusercontent.com/43223122/144897464-915bb87d-6e61-43cf-8f41-55f11e973b6c.png)
![Screen Shot 2021-12-06 at 14 56 59](https://user-images.githubusercontent.com/43223122/144897467-f72fb9f4-0809-4e84-80c8-c254e984ee04.png)
![Screen Shot 2021-12-06 at 14 57 31](https://user-images.githubusercontent.com/43223122/144897470-99090c27-a983-4f38-aafc-5db306b2e5a0.png)
![Screen Shot 2021-12-06 at 14 57 46](https://user-images.githubusercontent.com/43223122/144897471-667008ea-a288-464b-80f9-e18a72da4515.png)

2021-12-07 11:57 UTC, diegomart2000 approved these changes

2021-12-07 11:57 UTC, merged