search-bar-operand-cy-148-review-x1
caisy-io/league pull request #96
Opened 2021-12-02 12:55 UTC by steiningermona

fix issues from QA and apply recent feedback (destructure props and args and only pass needed props)

2021-12-06 12:48 UTC, steiningermona commented
screenshots from storybook:
![image](https://user-images.githubusercontent.com/93647258/144848472-773d273d-1f66-4ecd-bdc4-f23ab2566539.png)
![image](https://user-images.githubusercontent.com/93647258/144848654-fa03ef28-b781-48e6-a234-3d7ed9f8793f.png)
![image](https://user-images.githubusercontent.com/93647258/144848698-25515f15-0430-43aa-b977-a972def06261.png)
![image](https://user-images.githubusercontent.com/93647258/144848732-a2c03bf8-50f5-4ad7-9c3f-396b0489a85f.png)

screenshot from figma: 
![image](https://user-images.githubusercontent.com/93647258/144848596-5b525d6d-4d72-46ba-b2ca-cc16c5f03864.png)

2021-12-06 17:22 UTC, diegomart2000 requested changes
@steiningermona Operands could have multiple words.
<img width="887" alt="Screen Shot 2021-12-06 at 2 20 30 PM" src="https://user-images.githubusercontent.com/642960/144892089-79c9bac3-711a-4a58-90e3-4643cc970dd6.png">

but component is not rendering them properly

<img width="200" alt="Screen Shot 2021-12-06 at 2 21 49 PM" src="https://user-images.githubusercontent.com/642960/144892151-96f76ab3-95e9-45bc-8eab-b0bafa56ac75.png">

2021-12-07 07:56 UTC, steiningermona commented
@diegomart2000 thank you, totally forgot about that case! 
![image](https://user-images.githubusercontent.com/93647258/144988993-454f60c8-f1c5-43f8-8645-1996cac1444b.png)

2021-12-07 12:24 UTC, diegomart2000 approved these changes

2021-12-07 12:24 UTC, merged